server:
  port: 8081
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  datasource:
    hikari:
      connection-timeout: 10000
      maximum-pool-size: 10
    password: postgres
    url: jdbc:postgresql://localhost:5432/products
    username: postgres
